import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  skill: [
    'skill/introduction',
    // 'skill/git-common-operations',
     {
      label: '常用操作',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        'skill/common-operations/git-common-operations',
      ],
    },
    // {
    //   label: '常用操作',
    //   type: 'category',
    //   link: {
    //     type: 'doc',
    //     id: 'skill/common-operations/docusaurus-guides',
    //   },
    //   items: [
    //     'skill/docusaurus/docusaurus-deploy',
    //   ],
    // },
    // {
    //   label: 'Web',
    //   type: 'category',
    //   link: { type: 'generated-index' },
    //   items: [
    //     {
    //       label: 'Vue',
    //       type: 'category',
    //       link: { type: 'generated-index' },
    //       items: [
    //         'skill/web/vue/vue-reactive-data-object',
    //         'skill/web/vue/vue-reactive-data-array',
    //         'skill/web/vue/vue-reactive-data-basic-type',
    //         'skill/web/vue/pinia',
    //       ],
    //     },
    //     {
    //       label: 'React',
    //       type: 'category',
    //       link: { type: 'generated-index' },
    //       items: [
    //         {
    //           type: 'autogenerated',
    //           dirName: 'skill/web/react',
    //         },
    //       ],
    //     }
    //   ],
    // },
   
  ]
}

module.exports = sidebars
